/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API for the project.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderUpdateAdmin
 */
export interface OrderUpdateAdmin {
    /**
     * 
     * @type {string}
     * @memberof OrderUpdateAdmin
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderUpdateAdmin
     */
    product?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderUpdateAdmin
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderUpdateAdmin
     */
    price?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderUpdateAdmin
     */
    advancePayment?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderUpdateAdmin
     */
    pendingPayment?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderUpdateAdmin
     */
    registrationPlace?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderUpdateAdmin
     */
    shippingPlace?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderUpdateAdmin
     */
    phoneNumber?: string;
    /**
     * 
     * @type {Date}
     * @memberof OrderUpdateAdmin
     */
    shippingDate?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof OrderUpdateAdmin
     */
    hasProduction?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OrderUpdateAdmin
     */
    hasTopper?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OrderUpdateAdmin
     */
    hasDelivery?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OrderUpdateAdmin
     */
    completed?: boolean;
}

export function OrderUpdateAdminFromJSON(json: any): OrderUpdateAdmin {
    return OrderUpdateAdminFromJSONTyped(json, false);
}

export function OrderUpdateAdminFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderUpdateAdmin {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'product': !exists(json, 'product') ? undefined : json['product'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'price': !exists(json, 'price') ? undefined : json['price'],
        'advancePayment': !exists(json, 'advance_payment') ? undefined : json['advance_payment'],
        'pendingPayment': !exists(json, 'pending_payment') ? undefined : json['pending_payment'],
        'registrationPlace': !exists(json, 'registration_place') ? undefined : json['registration_place'],
        'shippingPlace': !exists(json, 'shipping_place') ? undefined : json['shipping_place'],
        'phoneNumber': !exists(json, 'phone_number') ? undefined : json['phone_number'],
        'shippingDate': !exists(json, 'shipping_date') ? undefined : (new Date(json['shipping_date'])),
        'hasProduction': !exists(json, 'has_production') ? undefined : json['has_production'],
        'hasTopper': !exists(json, 'has_topper') ? undefined : json['has_topper'],
        'hasDelivery': !exists(json, 'has_delivery') ? undefined : json['has_delivery'],
        'completed': !exists(json, 'completed') ? undefined : json['completed'],
    };
}

export function OrderUpdateAdminToJSON(value?: OrderUpdateAdmin | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'product': value.product,
        'description': value.description,
        'price': value.price,
        'advance_payment': value.advancePayment,
        'pending_payment': value.pendingPayment,
        'registration_place': value.registrationPlace,
        'shipping_place': value.shippingPlace,
        'phone_number': value.phoneNumber,
        'shipping_date': value.shippingDate === undefined ? undefined : (value.shippingDate.toISOString()),
        'has_production': value.hasProduction,
        'has_topper': value.hasTopper,
        'has_delivery': value.hasDelivery,
        'completed': value.completed,
    };
}


