/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API for the project.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderUpdateCompleted
 */
export interface OrderUpdateCompleted {
    /**
     * 
     * @type {boolean}
     * @memberof OrderUpdateCompleted
     */
    completed?: boolean;
}

export function OrderUpdateCompletedFromJSON(json: any): OrderUpdateCompleted {
    return OrderUpdateCompletedFromJSONTyped(json, false);
}

export function OrderUpdateCompletedFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderUpdateCompleted {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'completed': !exists(json, 'completed') ? undefined : json['completed'],
    };
}

export function OrderUpdateCompletedToJSON(value?: OrderUpdateCompleted | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'completed': value.completed,
    };
}


