/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API for the project.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderUpdateStore
 */
export interface OrderUpdateStore {
    /**
     * 
     * @type {string}
     * @memberof OrderUpdateStore
     */
    advancePayment?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderUpdateStore
     */
    pendingPayment?: string;
    /**
     * 
     * @type {Date}
     * @memberof OrderUpdateStore
     */
    shippingDate?: Date;
}

export function OrderUpdateStoreFromJSON(json: any): OrderUpdateStore {
    return OrderUpdateStoreFromJSONTyped(json, false);
}

export function OrderUpdateStoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderUpdateStore {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'advancePayment': !exists(json, 'advance_payment') ? undefined : json['advance_payment'],
        'pendingPayment': !exists(json, 'pending_payment') ? undefined : json['pending_payment'],
        'shippingDate': !exists(json, 'shipping_date') ? undefined : (new Date(json['shipping_date'])),
    };
}

export function OrderUpdateStoreToJSON(value?: OrderUpdateStore | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'advance_payment': value.advancePayment,
        'pending_payment': value.pendingPayment,
        'shipping_date': value.shippingDate === undefined ? undefined : (value.shippingDate.toISOString()),
    };
}


