/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API for the project.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderImageCreate
 */
export interface OrderImageCreate {
    /**
     * 
     * @type {string}
     * @memberof OrderImageCreate
     */
    readonly image?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrderImageCreate
     */
    order: string;
}

export function OrderImageCreateFromJSON(json: any): OrderImageCreate {
    return OrderImageCreateFromJSONTyped(json, false);
}

export function OrderImageCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderImageCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'image': !exists(json, 'image') ? undefined : json['image'],
        'order': json['order'],
    };
}

export function OrderImageCreateToJSON(value?: OrderImageCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'order': value.order,
    };
}


