/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API for the project.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderImage
 */
export interface OrderImage {
    /**
     * 
     * @type {string}
     * @memberof OrderImage
     */
    readonly image?: string | null;
}

export function OrderImageFromJSON(json: any): OrderImage {
    return OrderImageFromJSONTyped(json, false);
}

export function OrderImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderImage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'image': !exists(json, 'image') ? undefined : json['image'],
    };
}

export function OrderImageToJSON(value?: OrderImage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}


