/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API for the project.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserCompanyStore
 */
export interface UserCompanyStore {
    /**
     * 
     * @type {string}
     * @memberof UserCompanyStore
     */
    name: string;
}

export function UserCompanyStoreFromJSON(json: any): UserCompanyStore {
    return UserCompanyStoreFromJSONTyped(json, false);
}

export function UserCompanyStoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserCompanyStore {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function UserCompanyStoreToJSON(value?: UserCompanyStore | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}


